-- 전월세 부동산 금융 플랫폼 초기 스키마
-- database.md §3 (30개 테이블) · §6 (PostgreSQL 적용 규약) 기준
-- 테이블 생성 순서는 FK 의존성을 지켜 부모를 먼저 생성한다.
-- 열거형 컬럼은 VARCHAR로 두고 CHECK 제약은 걸지 않는다 (애플리케이션 enum이 관리, §6).

-- 1. PROPERTY_CODE — 매물 코드
CREATE TABLE property_code (
    code_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_group       VARCHAR(30)  NOT NULL,
    code_value       VARCHAR(30)  NOT NULL,
    code_name        VARCHAR(50)  NOT NULL,
    code_description VARCHAR(200),
    sort_order       INTEGER      NOT NULL DEFAULT 0,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_property_code_group_value UNIQUE (code_group, code_value)
);

-- 2. USER — 사용자 ("user"는 예약어이므로 users로 생성)
CREATE TABLE users (
    user_id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                         VARCHAR(50)  NOT NULL,
    email                        VARCHAR(100),
    phone                        VARCHAR(20),
    role                         VARCHAR(20)  NOT NULL DEFAULT 'USER',
    annual_income                BIGINT       NOT NULL DEFAULT 0,
    credit_score                 INTEGER      NOT NULL,
    existing_loan                BIGINT       NOT NULL DEFAULT 0,
    existing_loan_annual_payment BIGINT       NOT NULL DEFAULT 0,
    has_house                    BOOLEAN      NOT NULL DEFAULT FALSE,
    own_fund                     BIGINT       NOT NULL DEFAULT 0,
    created_at                   TIMESTAMP    NOT NULL DEFAULT now(),
    deleted_at                   TIMESTAMP
);

-- 3. USER_AUTH — 사용자 인증
CREATE TABLE user_auth (
    auth_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL REFERENCES users (user_id),
    auth_type     VARCHAR(10)  NOT NULL,
    provider_id   VARCHAR(100),
    password_hash VARCHAR(255),
    last_login_at TIMESTAMP,
    created_at    TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_auth_type_provider UNIQUE (auth_type, provider_id)
);

-- 4. PROPERTY — 매물
CREATE TABLE property (
    property_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address               VARCHAR(200)  NOT NULL,
    district              VARCHAR(30)   NOT NULL,
    landlord_name         VARCHAR(50)   NOT NULL,
    contract_type_code_id BIGINT        NOT NULL REFERENCES property_code (code_id),
    property_type_code_id BIGINT        NOT NULL REFERENCES property_code (code_id),
    status_code_id        BIGINT        NOT NULL REFERENCES property_code (code_id),
    deposit               BIGINT        NOT NULL DEFAULT 0,
    monthly_rent          BIGINT        DEFAULT 0,
    market_price          BIGINT        NOT NULL,
    price_type            VARCHAR(20),
    price_date            DATE,
    area_sqm              NUMERIC(7, 2) NOT NULL,
    floor                 INTEGER,
    built_year            INTEGER,
    latitude              NUMERIC(10, 7),
    longitude             NUMERIC(10, 7),
    registered_at         TIMESTAMP     NOT NULL DEFAULT now()
);

-- 5. SEARCH_HISTORY — 검색 이력
CREATE TABLE search_history (
    search_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES users (user_id),
    property_id     BIGINT       REFERENCES property (property_id),
    search_keyword  VARCHAR(100) NOT NULL,
    search_district VARCHAR(30)  NOT NULL,
    contract_type   VARCHAR(10)  NOT NULL,
    searched_at     TIMESTAMP    NOT NULL DEFAULT now()
);

-- 6. BUILDING_LEDGER — 건축물관리대장
CREATE TABLE building_ledger (
    ledger_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id        BIGINT        NOT NULL REFERENCES property (property_id),
    ledger_address     VARCHAR(200)  NOT NULL,
    owner_name         VARCHAR(50)   NOT NULL,
    building_purpose   VARCHAR(50)   NOT NULL,
    building_structure VARCHAR(50),
    building_area      NUMERIC(7, 2) NOT NULL,
    violation_yn       BOOLEAN       NOT NULL DEFAULT FALSE,
    updated_at         TIMESTAMP     NOT NULL DEFAULT now()
);

-- 7. BUILDING_REGISTRY — 표제부 (등기부등본)
CREATE TABLE building_registry (
    registry_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id        BIGINT      NOT NULL REFERENCES property (property_id),
    building_purpose   VARCHAR(50) NOT NULL,
    building_structure VARCHAR(50),
    updated_at         TIMESTAMP   NOT NULL DEFAULT now()
);

-- 8. OWNERSHIP_HISTORY — 갑구 (소유권 이력)
CREATE TABLE ownership_history (
    ownership_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registry_id                  BIGINT      NOT NULL REFERENCES building_registry (registry_id),
    owner_name                   VARCHAR(50) NOT NULL,
    ownership_date               DATE,
    provisional_seizure_yn       BOOLEAN     NOT NULL DEFAULT FALSE,
    seizure_yn                   BOOLEAN     NOT NULL DEFAULT FALSE,
    auction_yn                   BOOLEAN     NOT NULL DEFAULT FALSE,
    provisional_registration_yn  BOOLEAN     NOT NULL DEFAULT FALSE,
    trust_registration_yn        BOOLEAN     NOT NULL DEFAULT FALSE,
    lease_registration_yn        BOOLEAN     NOT NULL DEFAULT FALSE,
    is_current                   BOOLEAN     NOT NULL DEFAULT TRUE,
    recorded_at                  TIMESTAMP   NOT NULL DEFAULT now()
);

-- 9. MORTGAGE_HISTORY — 을구 (채무 이력)
CREATE TABLE mortgage_history (
    mortgage_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registry_id          BIGINT       NOT NULL REFERENCES building_registry (registry_id),
    priority_no          INTEGER      NOT NULL,
    right_type           VARCHAR(20)  NOT NULL,
    receipt_date         DATE,
    registration_cause   VARCHAR(50),
    mortgage_amount      BIGINT       DEFAULT 0,
    mortgage_creditor    VARCHAR(100),
    debtor_name          VARCHAR(50),
    max_bond_amount      BIGINT       NOT NULL DEFAULT 0,
    prior_tenant_deposit BIGINT       DEFAULT 0,
    lease_right_yn       BOOLEAN      NOT NULL DEFAULT FALSE,
    tenancy_right_yn     BOOLEAN      NOT NULL DEFAULT FALSE,
    senior_debt_yn       BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active            BOOLEAN      NOT NULL DEFAULT TRUE,
    recorded_at          TIMESTAMP    NOT NULL DEFAULT now()
);

-- 10. GUARANTEE_CRITERIA — 보증보험 공통 기준
CREATE TABLE guarantee_criteria (
    guarantee_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider                     VARCHAR(10)   NOT NULL,
    max_deposit                  BIGINT        NOT NULL,
    collateral_ratio             NUMERIC(5, 2) NOT NULL DEFAULT 90.00,
    guarantee_ratio              NUMERIC(5, 2) NOT NULL,
    lease_ratio_limit            NUMERIC(5, 2) NOT NULL DEFAULT 90.00,
    strict_singlehouse_yn        BOOLEAN       NOT NULL DEFAULT FALSE,
    require_confirmed_date_yn    BOOLEAN       NOT NULL DEFAULT TRUE,
    violation_disqualify_yn      BOOLEAN       NOT NULL DEFAULT TRUE,
    right_violation_disqualify_yn BOOLEAN      NOT NULL DEFAULT TRUE,
    updated_at                   TIMESTAMP     NOT NULL DEFAULT now(),
    CONSTRAINT uq_guarantee_criteria_provider UNIQUE (provider)
);

-- 11. HUG_CRITERIA — HUG 세부 기준
CREATE TABLE hug_criteria (
    hug_criteria_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guarantee_id        BIGINT  NOT NULL REFERENCES guarantee_criteria (guarantee_id),
    metro_deposit_limit BIGINT  NOT NULL DEFAULT 700000000,
    ltv_premium_tiered_yn BOOLEAN NOT NULL DEFAULT TRUE,
    newlywed_discount_yn  BOOLEAN NOT NULL DEFAULT FALSE,
    multichild_discount_yn BOOLEAN NOT NULL DEFAULT FALSE,
    social_discount_yn    BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at          TIMESTAMP NOT NULL DEFAULT now()
);

-- 12. HF_CRITERIA — HF 세부 기준
CREATE TABLE hf_criteria (
    hf_criteria_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guarantee_id          BIGINT  NOT NULL REFERENCES guarantee_criteria (guarantee_id),
    loan_linked_required_yn BOOLEAN NOT NULL DEFAULT TRUE,
    lowest_premium_yn     BOOLEAN NOT NULL DEFAULT TRUE,
    youth_discount_yn     BOOLEAN NOT NULL DEFAULT FALSE,
    newlywed_discount_yn  BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at            TIMESTAMP NOT NULL DEFAULT now()
);

-- 13. SGI_CRITERIA — SGI 세부 기준
CREATE TABLE sgi_criteria (
    sgi_criteria_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guarantee_id          BIGINT  NOT NULL REFERENCES guarantee_criteria (guarantee_id),
    apartment_unlimited_yn BOOLEAN NOT NULL DEFAULT TRUE,
    other_house_limit     BIGINT  NOT NULL DEFAULT 1000000000,
    private_insurer_yn    BOOLEAN NOT NULL DEFAULT TRUE,
    high_value_available_yn BOOLEAN NOT NULL DEFAULT TRUE,
    broker_contract_required_yn BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at            TIMESTAMP NOT NULL DEFAULT now()
);

-- 14. GUARANTEE_PREMIUM_RATE — 보증료율 (주택유형·부채비율 구간별)
CREATE TABLE guarantee_premium_rate (
    premium_rate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guarantee_id    BIGINT        NOT NULL REFERENCES guarantee_criteria (guarantee_id),
    house_type      VARCHAR(20)   NOT NULL,
    debt_ratio_min  NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
    debt_ratio_max  NUMERIC(5, 2) NOT NULL,
    premium_rate    NUMERIC(5, 3) NOT NULL,
    updated_at      TIMESTAMP     NOT NULL DEFAULT now()
);

-- 15. INSURANCE_PRODUCT — 전세보증보험 상품
CREATE TABLE insurance_product (
    insurance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guarantee_id BIGINT       NOT NULL REFERENCES guarantee_criteria (guarantee_id),
    product_name VARCHAR(100) NOT NULL,
    updated_at   TIMESTAMP    NOT NULL DEFAULT now()
);

-- 16. RISK_ANALYSIS — 위험도 분석 (이력성 엔티티)
CREATE TABLE risk_analysis (
    risk_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id           BIGINT        NOT NULL REFERENCES property (property_id),
    registry_id           BIGINT        NOT NULL REFERENCES building_registry (registry_id),
    ledger_id             BIGINT        NOT NULL REFERENCES building_ledger (ledger_id),
    eligible_guarantee_id BIGINT        REFERENCES guarantee_criteria (guarantee_id),
    lease_ratio           NUMERIC(5, 2) NOT NULL,
    hug_eligible_yn       BOOLEAN       NOT NULL DEFAULT FALSE,
    hf_eligible_yn        BOOLEAN       NOT NULL DEFAULT FALSE,
    sgi_eligible_yn       BOOLEAN       NOT NULL DEFAULT FALSE,
    insurance_eligible_yn BOOLEAN       NOT NULL DEFAULT FALSE,
    risk_grade            VARCHAR(10)   NOT NULL,
    previous_grade        VARCHAR(10),
    risk_reason           TEXT,
    is_latest             BOOLEAN       NOT NULL DEFAULT TRUE,
    analyzed_at           TIMESTAMP     NOT NULL DEFAULT now()
);

-- 17. LOAN_REGULATION — 대출 규제
CREATE TABLE loan_regulation (
    regulation_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_type       VARCHAR(30)   NOT NULL,
    region_type      VARCHAR(30)   NOT NULL,
    ltv_limit        NUMERIC(5, 2) NOT NULL,
    dsr_limit        NUMERIC(5, 2) NOT NULL DEFAULT 40.00,
    stress_dsr_rate  NUMERIC(5, 2) NOT NULL,
    stress_dsr_limit NUMERIC(5, 2) NOT NULL,
    dti_limit        NUMERIC(5, 2) NOT NULL,
    effective_date   DATE          NOT NULL
);

-- 18. LOAN_PRODUCT — 대출 상품
CREATE TABLE loan_product (
    loan_id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name                 VARCHAR(50)   NOT NULL,
    product_name              VARCHAR(100)  NOT NULL,
    loan_type                 VARCHAR(30)   NOT NULL,
    interest_rate             NUMERIC(5, 3) NOT NULL,
    rate_type                 VARCHAR(10)   NOT NULL,
    max_limit                 BIGINT        NOT NULL,
    loan_term                 INTEGER       NOT NULL,
    repayment_type            VARCHAR(20)   NOT NULL,
    income_condition          BIGINT,
    house_ownership_condition BOOLEAN       NOT NULL DEFAULT FALSE,
    updated_at                TIMESTAMP     NOT NULL DEFAULT now()
);

-- 19. INTEREST_RATE_HISTORY — 금리 변동 이력
CREATE TABLE interest_rate_history (
    rate_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate_type   VARCHAR(20)   NOT NULL,
    rate_value  NUMERIC(5, 3) NOT NULL,
    change_date DATE          NOT NULL,
    source      VARCHAR(50)
);

-- 20. LOAN_PLAN — 맞춤형 대출 계획
CREATE TABLE loan_plan (
    plan_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT        NOT NULL REFERENCES users (user_id),
    property_id        BIGINT        NOT NULL REFERENCES property (property_id),
    risk_id            BIGINT        NOT NULL REFERENCES risk_analysis (risk_id),
    loan_id            BIGINT        NOT NULL REFERENCES loan_product (loan_id),
    regulation_id      BIGINT        NOT NULL REFERENCES loan_regulation (regulation_id),
    recommended_amount BIGINT        NOT NULL,
    monthly_payment    BIGINT        NOT NULL,
    ltv_result         NUMERIC(5, 2) NOT NULL,
    dsr_result         NUMERIC(5, 2) NOT NULL,
    stress_dsr_result  NUMERIC(5, 2) NOT NULL,
    created_at         TIMESTAMP     NOT NULL DEFAULT now()
);

-- 21. CONSULTATION — 상담 이력
CREATE TABLE consultation (
    consult_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES users (user_id),
    plan_id         BIGINT       REFERENCES loan_plan (plan_id),
    property_id     BIGINT       REFERENCES property (property_id),
    consult_type    VARCHAR(10)  NOT NULL,
    consultant_name VARCHAR(50)  NOT NULL,
    consult_status  VARCHAR(10)  NOT NULL DEFAULT 'WAITING',
    summary         TEXT         NOT NULL,
    scheduled_at    TIMESTAMP    NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT now()
);

-- 22. CONSULT_MESSAGE — 상담 메시지
CREATE TABLE consult_message (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consult_id BIGINT      NOT NULL REFERENCES consultation (consult_id),
    sender     VARCHAR(10) NOT NULL,
    message    TEXT        NOT NULL,
    sent_at    TIMESTAMP   NOT NULL DEFAULT now()
);

-- 23. WISHLIST — 관심 매물
CREATE TABLE wishlist (
    wish_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT      NOT NULL REFERENCES users (user_id),
    property_id    BIGINT      NOT NULL REFERENCES property (property_id),
    monitoring_yn  BOOLEAN     NOT NULL DEFAULT FALSE,
    alert_condition VARCHAR(50) NOT NULL,
    created_at     TIMESTAMP   NOT NULL DEFAULT now()
);

-- 24. NOTIFICATION_SUBSCRIPTION — 알림 구독 설정
CREATE TABLE notification_subscription (
    subscription_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      NOT NULL REFERENCES users (user_id),
    subscription_type VARCHAR(20) NOT NULL,
    target_district   VARCHAR(30) NOT NULL,
    contract_type     VARCHAR(10) NOT NULL,
    deposit_min       BIGINT      NOT NULL DEFAULT 0,
    deposit_max       BIGINT      NOT NULL,
    is_active         BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMP   NOT NULL DEFAULT now()
);

-- 25. NOTIFICATION — 알림 공통 상위 테이블
CREATE TABLE notification (
    notif_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (user_id),
    notif_type VARCHAR(20) NOT NULL,
    is_read    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP   NOT NULL DEFAULT now()
);

-- 26. PROPERTY_NOTIFICATION — 매물 알림
CREATE TABLE property_notification (
    prop_notif_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notif_id        BIGINT NOT NULL REFERENCES notification (notif_id),
    property_id     BIGINT NOT NULL REFERENCES property (property_id),
    subscription_id BIGINT NOT NULL REFERENCES notification_subscription (subscription_id)
);

-- 27. RATE_NOTIFICATION — 금리 변동 알림
CREATE TABLE rate_notification (
    rate_notif_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notif_id        BIGINT        NOT NULL REFERENCES notification (notif_id),
    rate_id         BIGINT        NOT NULL REFERENCES interest_rate_history (rate_id),
    subscription_id BIGINT        NOT NULL REFERENCES notification_subscription (subscription_id),
    previous_rate   NUMERIC(5, 3) NOT NULL,
    current_rate    NUMERIC(5, 3) NOT NULL
);

-- 28. CONSULT_NOTIFICATION — 상담 일정 알림
CREATE TABLE consult_notification (
    consult_notif_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notif_id         BIGINT    NOT NULL REFERENCES notification (notif_id),
    consult_id       BIGINT    NOT NULL REFERENCES consultation (consult_id),
    scheduled_at     TIMESTAMP NOT NULL,
    remind_time      TIMESTAMP NOT NULL
);

-- 29. WISHLIST_NOTIFICATION — 관심 매물 모니터링 알림
CREATE TABLE wishlist_notification (
    wish_notif_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notif_id      BIGINT       NOT NULL REFERENCES notification (notif_id),
    wish_id       BIGINT       NOT NULL REFERENCES wishlist (wish_id),
    change_type   VARCHAR(20)  NOT NULL,
    before_value  VARCHAR(100) NOT NULL,
    after_value   VARCHAR(100) NOT NULL,
    detected_at   TIMESTAMP    NOT NULL DEFAULT now()
);

-- 30. REGION_STATS — 지역 시세 통계
CREATE TABLE region_stats (
    stat_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district          VARCHAR(30)   NOT NULL,
    contract_type     VARCHAR(10)   NOT NULL,
    avg_deposit       BIGINT        NOT NULL,
    avg_monthly_rent  BIGINT        NOT NULL DEFAULT 0,
    avg_lease_ratio   NUMERIC(5, 2) NOT NULL,
    transaction_count INTEGER       NOT NULL DEFAULT 0,
    price_change_rate NUMERIC(6, 2) NOT NULL,
    risk_index        NUMERIC(5, 2) NOT NULL,
    stat_date         DATE          NOT NULL,
    CONSTRAINT uq_region_stats_district_type_date UNIQUE (district, contract_type, stat_date)
);
