-- 판정 기준 테이블을 근거 조사 결과에 맞춘다 — 데이터베이스 설계서 10 · 14 · 31 · 32절, 비즈니스 로직 정의서 2 · 3 · 4장.
-- 기준 테이블에는 아직 행이 없으므로(시드는 V7) NOT NULL 추가 · 컬럼 삭제가 안전하다.

-- 10. GUARANTEE_CRITERIA
--   guarantee_ratio: 반환보증에는 「보증비율」 개념이 없다. 문서의 「HUG 60% 하향(2025.9)」은 사실이 아니었고
--   (2025년 변경은 전세대출보증의 보증비율), 넣을 값이 없다.
--   lease_ratio_limit: 담보인정비율과 같은 90% 하나가 보증한도 산식과 가입 상한에 함께 쓰인다. 두 컬럼이면 갈라진다.
--   senior_debt_ratio_limit: 실재하는 60% — 선순위채권 단독 한도. 값이 확인되지 않은 기관은 NULL 로 두고 검사하지 않는다.
ALTER TABLE guarantee_criteria DROP COLUMN guarantee_ratio;
ALTER TABLE guarantee_criteria DROP COLUMN lease_ratio_limit;
ALTER TABLE guarantee_criteria ADD COLUMN senior_debt_ratio_limit NUMERIC(5, 2);

-- 14. GUARANTEE_PREMIUM_RATE — HUG 요율(2025.3.31~)은 보증금 4구간이 축이다. 보증금 축이 없는 기관은 0 ~ NULL 한 구간.
ALTER TABLE guarantee_premium_rate ADD COLUMN deposit_min BIGINT NOT NULL DEFAULT 0;
ALTER TABLE guarantee_premium_rate ADD COLUMN deposit_max BIGINT;

-- 31. CRITERIA_CHANGE_HISTORY — 판정 기준 변경 이력 (ADMIN-01)
--   필드 하나의 변경이 한 행이고, 한 번의 수정 요청에서 바뀐 필드들은 change_group_id 로 묶는다.
--   대상은 기준 테이블 7종 중 하나(다형 참조)라 FK 를 두지 않는다. 대상 행이 사라져도 이력은 남는다.
--   불변 이력이라 updated_at 이 없다.
CREATE TABLE criteria_change_history (
    history_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    change_group_id UUID         NOT NULL,
    target_table    VARCHAR(30)  NOT NULL,
    target_id       BIGINT       NOT NULL,
    target_key      VARCHAR(80)  NOT NULL,
    field_name      VARCHAR(50)  NOT NULL,
    before_value    VARCHAR(100),
    after_value     VARCHAR(100) NOT NULL,
    change_reason   VARCHAR(200) NOT NULL,
    changed_by      BIGINT       NOT NULL REFERENCES users (user_id),
    changed_at      TIMESTAMP    NOT NULL DEFAULT now()
);
-- 시점 재구성: 특정 대상 · 필드의 changed_at <= T 중 가장 늦은 행
CREATE INDEX ix_criteria_change_history_target
    ON criteria_change_history (target_table, target_id, field_name, changed_at DESC);
-- 이력 조회 커서 (changedAt DESC, historyId DESC)
CREATE INDEX ix_criteria_change_history_cursor
    ON criteria_change_history (changed_at DESC, history_id DESC);

-- 32. RISK_CRITERIA — 위험 등급 기준 (단일 행)
CREATE TABLE risk_criteria (
    risk_criteria_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    negative_equity_ratio NUMERIC(5, 2) NOT NULL DEFAULT 80.00,
    caution_lease_ratio   NUMERIC(5, 2) NOT NULL DEFAULT 70.00,
    created_at            TIMESTAMP     NOT NULL DEFAULT now(),
    updated_at            TIMESTAMP     NOT NULL DEFAULT now(),
    -- CAUTION 경계가 깡통전세 선 이상이면 CAUTION 이 나올 수 없다 — 비즈니스 로직 정의서 3장
    CONSTRAINT ck_risk_criteria_monotonic CHECK (caution_lease_ratio < negative_equity_ratio)
);
